import type { Metadata } from "next";
import React from "react";
import "@/app/globals.css"


export const metadata : Metadata = {
    title : "Create Next App",
    description : "Generated by create next app"
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return(
        children
    )
}

